version: '3'

services:
  lingua-card:
    build: .
    container_name: lingua-card
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html
      # Uncomment the line below if you want to make config changes without rebuilding
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
